apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
 name: daytrader
 namespace: default
spec:
 scaleRef:
   kind: Deployment
   name: daytrader
   subresource: scale
 minReplicas: 1
 maxReplicas: 10
 cpuUtilization:
   targetPercentage: 50
