apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-daytrader
 namespace: default
spec:
 scaleTargetRef:
   apiVersion: apps/v1beta1
   kind: Deployment
   name: daytrader
 minReplicas: 1
 maxReplicas: 3
 metrics:
 - type: Resource
   resource:
     name: cpu
     targetAverageUtilization: 50
